<div>

  <h2>Where does the data come from?</h2>
  <p class="text-sm mt-1">
    The graph data is generated from the
    <a
      href="http://s2-public-api-prod.us-west-2.elasticbeanstalk.com/corpus/download/"
      target="_blank">
      Semantic Scholar Open Research Corpus
    </a>
    using the binaries in
    <a href="https://github.com/dennybritz/papergraph/" target="_blank">
      dennybritz/papergraph
    </a>
    . It is stored in a postgres database with a Hasura API frontend.
  </p>

  <h2 class="mt-4">How is the displayed graph generated?</h2>
  <p class="text-sm mt-1">
    The graph is generated by finding the root node based on the search query,
    and the following the top 20 citations by total citation count of each paper
    over two hops (citations of citatations). Thus, each graph can have at most
    20*20+1 nodes. Pruning to 20 links helps with visualization performance. In
    the future, there may be options to adjust the pruning. For more details,
    please look at the
    <a href="https://github.com/dennybritz/papergraph-ui/" target="_blank">
      source code
    </a>
    .
  </p>

  <h2 class="mt-4">Can I run more complex queries?</h2>
  <p class="text-sm mt-1">
    For slightly more complex queries you can
    <a href="https://github.com/dennybritz/papergraph/" target="_blank">
      adjust the code for your own purposes
    </a>
    . However, significantly more complex queries would require a true graph
    database, such as
    <a href="https://dgraph.io/" target="_blank">dgraph</a>
    as a backend. Currently the data lives in postgres. A database such as
    dgraph is signifcantly more expensive to host. If you are willing to sponsor
    the project to cover the costs for hosting such a database (estimated
    ~$300-400/mo) I am willing to
    <a href="https://github.com/dennybritz/papergraph/pull/26" target="_blank">
      migrate it
    </a>
    . Please get in touch.
  </p>

  <h2 class="mt-4">Can I download the raw data?</h2>
  <p class="text-sm mt-1">
    You can access the currently displayed subgraph data using the
    <code>subGraphData</code>
    variable your browser JS console. However, there currently is no easy way to
    download a full graph dump due to the size of it and limited resources. The
    code to generate the database is open source at
    <a href="https://github.com/dennybritz/papergraph/" target="_blank">
      dennybritz/papergraph
    </a>
    and you may want to take a look at that.
  </p>

  <h2 class="mt-4">X does not work!</h2>
  <p class="text-sm mt-1">
    Please
    <a
      href="https://github.com/dennybritz/papergraph-ui/issues"
      target="_blank">
      open an issue in the Github repository
    </a>
    .
  </p>

</div>

<!-- <div>Coming soon.</div> -->
